version: '3.4'

services:
  samba:
    container_name: samba
    image: dperson/samba
    environment:
      TZ: 'Europe/Warsaw'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /home/samba:/mnt
    command: '-S -s "Mount;/mnt;yes;no;yes;all;" -p'
